Fixing compilation warnings causing build to fail
 * Bellow is the excerpt of the compilation output showing the warning causing
   compilation to fail:
   vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
   ...
   /build/vendor/googletest/googletest/src/gtest-internal-inl.h:322:32: error: implicit conversion changes signedness:
         'unsigned int' to 'const int' [-Werror,-Wsign-conversion]
       const int selected = begin + random->Generate(range_width);
                 ~~~~~~~~   ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   ...
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^